const KEY="amar-betan-v1";
const defaultData={settings:{monthlySalary:0,monthlyTransport:0,monthlyFood:0,monthlyBonus:0,otRate:50,reminderEnabled:false,reminderTime:"21:00"},records:{}};
let data=load(), viewDate=new Date(), selectedDate=null, selectedStatus="PRESENT";
const $=id=>document.getElementById(id);
function load(){try{return {...defaultData,...JSON.parse(localStorage.getItem(KEY)||"{}"),settings:{...defaultData.settings,...(JSON.parse(localStorage.getItem(KEY)||"{}").settings||{})}}}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function money(n){return "৳"+Math.round(n||0).toLocaleString("bn-BD")}
function monthKey(d=viewDate){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function dateKey(y,m,d){return `${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`}
function recordsForMonth(){let p=monthKey();return Object.entries(data.records).filter(([k])=>k.startsWith(p))}
function calc(){let s=data.settings,r=recordsForMonth(), present=r.filter(([,v])=>v.status==="PRESENT"), absent=r.filter(([,v])=>v.status==="ABSENT");let dailySal=s.monthlySalary/30,dailyTr=s.monthlyTransport/30,dailyFood=s.monthlyFood/30;let salary=present.length*dailySal,transport=present.length*dailyTr,food=present.length*dailyFood;let bonus=absent.length?0:(present.length? s.monthlyBonus:0);let ot=0,otHours=0;for(const [,v] of present){otHours+=Number(v.otHours)||0;ot+=(Number(v.otHours)||0)*(Number(v.otRateSnapshot??s.otRate)||0)}return {salary,transport,food,bonus,ot,otHours,total:salary+transport+food+bonus+ot,present:present.length,absent:absent.length}}
function render(){let c=calc();$("totalIncome").textContent=money(c.total);$("salaryEarned").textContent=money(c.salary);$("transportEarned").textContent=money(c.transport);$("foodEarned").textContent=money(c.food);$("bonusEarned").textContent=money(c.bonus);$("otEarned").textContent=money(c.ot);$("presentCount").textContent=c.present;$("absentCount").textContent=c.absent;$("otTotal").textContent=c.otHours.toLocaleString("bn-BD");let title=viewDate.toLocaleDateString("bn-BD",{month:"long",year:"numeric"});$("monthLabel").textContent=title;$("calendarTitle").textContent=title;renderCalendar();$("reminderStatus").textContent=data.settings.reminderEnabled?`চালু — ${data.settings.reminderTime}`:"বন্ধ"}
function renderCalendar(){let el=$("calendar");el.innerHTML="";let y=viewDate.getFullYear(),m=viewDate.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prevDays=new Date(y,m,0).getDate();for(let i=0;i<first;i++){let d=document.createElement("div");d.className="day muted";d.textContent=prevDays-first+i+1;el.appendChild(d)}for(let day=1;day<=days;day++){let d=document.createElement("button");d.className="day";let k=dateKey(y,m,day),rec=data.records[k];d.innerHTML=`<span class="daynum">${day.toLocaleString("bn-BD")}</span>`;if(rec?.status==="PRESENT")d.classList.add("present");if(rec?.status==="ABSENT")d.classList.add("absent");let now=new Date();if(day===now.getDate()&&m===now.getMonth()&&y===now.getFullYear())d.classList.add("today");if(rec?.otHours>0)d.innerHTML+=`<span class="otbadge">OT ${rec.otHours}</span>`;d.onclick=()=>openDay(k);el.appendChild(d)}while(el.children.length<42){let d=document.createElement("div");d.className="day muted";el.appendChild(d)}}
function openDay(k){selectedDate=k;let rec=data.records[k];selectedStatus=rec?.status||"PRESENT";$("modalTitle").textContent=`${new Date(k+"T00:00:00").toLocaleDateString("bn-BD",{day:"numeric",month:"long",year:"numeric"})}`;$("otHours").value=rec?.otHours||0;$("modalOtRate").textContent=money(data.settings.otRate)+"/ঘণ্টা";document.querySelectorAll(".seg button").forEach(b=>b.classList.toggle("active",b.dataset.status===selectedStatus));$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
document.querySelectorAll(".seg button").forEach(b=>b.onclick=()=>{selectedStatus=b.dataset.status;document.querySelectorAll(".seg button").forEach(x=>x.classList.toggle("active",x===b));if(selectedStatus==="ABSENT")$("otHours").value=0});
$("saveDay").onclick=()=>{let h=Math.max(0,Number($("otHours").value)||0);if(selectedStatus==="ABSENT")h=0;data.records[selectedDate]={status:selectedStatus,otHours:h,otRateSnapshot:Number(data.settings.otRate)||0,savedAt:new Date().toISOString()};save();closeModal();render();toast("সংরক্ষণ হয়েছে")};
$("clearDay").onclick=()=>{delete data.records[selectedDate];save();closeModal();render();toast("তথ্য মুছে ফেলা হয়েছে")};
$("prevMonth").onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);render()};
$("nextMonth").onclick=()=>{viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);render()};
$("settingsBtn").onclick=()=>{let s=data.settings;$("sSalary").value=s.monthlySalary;$("sTransport").value=s.monthlyTransport;$("sFood").value=s.monthlyFood;$("sBonus").value=s.monthlyBonus;$("sOtRate").value=s.otRate;$("sReminder").checked=s.reminderEnabled;$("sReminderTime").value=s.reminderTime;$("settingsModal").classList.remove("hidden")};
$("closeSettings").onclick=()=>$("settingsModal").classList.add("hidden");
$("saveSettings").onclick=async()=>{let s=data.settings;s.monthlySalary=Math.max(0,Number($("sSalary").value)||0);s.monthlyTransport=Math.max(0,Number($("sTransport").value)||0);s.monthlyFood=Math.max(0,Number($("sFood").value)||0);s.monthlyBonus=Math.max(0,Number($("sBonus").value)||0);s.otRate=Math.max(0,Number($("sOtRate").value)||0);s.reminderEnabled=$("sReminder").checked;s.reminderTime=$("sReminderTime").value||"21:00";save();$("settingsModal").classList.add("hidden");render();if(s.reminderEnabled&&"Notification"in window&&Notification.permission==="default")await Notification.requestPermission();toast("Settings সংরক্ষণ হয়েছে")};
$("backupBtn").onclick=()=>{let blob=new Blob([JSON.stringify({app:"amar-betan",version:1,exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"});let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`amar-betan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$("restoreInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let obj=JSON.parse(await f.text());if(obj.app!=="amar-betan"||!obj.data?.settings||!obj.data?.records)throw Error();if(confirm("Backup restore করবেন? OK = Full Replace")){data=obj.data;save();render();toast("Restore সম্পন্ন হয়েছে")}}catch{alert("Backup file সঠিক নয়।")};e.target.value=""};
$("slipBtn").onclick=()=>{let c=calc(),s=data.settings; $("slipContent").innerHTML=`<h2>আমার বেতন — ${viewDate.toLocaleDateString("bn-BD",{month:"long",year:"numeric"})}</h2><div class="row"><span>উপস্থিত</span><b>${c.present}</b></div><div class="row"><span>অনুপস্থিত</span><b>${c.absent}</b></div><div class="row"><span>OT ঘণ্টা</span><b>${c.otHours}</b></div><div class="row"><span>OT রেট</span><b>${money(s.otRate)}/ঘণ্টা</b></div><div class="row"><span>মূল বেতন</span><b>${money(c.salary)}</b></div><div class="row"><span>যাতায়াত</span><b>${money(c.transport)}</b></div><div class="row"><span>খাবার</span><b>${money(c.food)}</b></div><div class="row"><span>অ্যাটেনডেন্স বোনাস</span><b>${money(c.bonus)}</b></div><div class="row"><span>OT</span><b>${money(c.ot)}</b></div><hr><div class="row"><strong>মোট ইনকাম</strong><strong>${money(c.total)}</strong></div>`;$("slipModal").classList.remove("hidden")};
$("closeSlip").onclick=()=>$("slipModal").classList.add("hidden");$("printSlip").onclick=()=>window.print();
$("closeModal").onclick=closeModal;
function toast(t){let x=$("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",1800)}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
setInterval(()=>{if(!data.settings.reminderEnabled)return;let now=new Date(),t=now.toTimeString().slice(0,5);if(t===data.settings.reminderTime&&localStorage.getItem("lastReminder")!==`${now.toDateString()} ${t}`){localStorage.setItem("lastReminder",`${now.toDateString()} ${t}`);if("Notification"in window&&Notification.permission==="granted")new Notification("আমার বেতন",{body:"আজকের উপস্থিতি মার্ক করুন"});toast("🔔 আজকের উপস্থিতি মার্ক করুন")}},30000);
render();